### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bortooo** [Xalcon/AnalyzeIO#6] opened 2017-06-19 18:03 UTC
When I tried to load my modpack it crashes, I disabled this mod and now it works.
[Crash report](https://pastebin.com/gXcm6bYx)

**Comment by Xalcon** [comment] 2017-06-19 18:48
I've setup a modpack and installed every single mod from your crashlog and I wasnt able to replicate the issue. Please make sure you are on the latest version for each mod.
AnalyseIO doesnt seem to be the culprit.

**Comment by bortooo** [comment] 2017-06-20 12:17
I really don't understand. I updated some mod and now it works with AnalyzeIO.
[My current modpack](https://pastebin.com/3qMyJCM2)
But I'm sure it was this mod. I disabled only AnalyzeIO and it worked.
Maybe it was some config or some MineTweaker script, but I don't know, anyway do you know what is the reason of the crash?
Thanks for your time!

**Comment by Xalcon** [comment] 2017-06-20 12:18
I have no idea. The Crash was also not related to AnalyzeIO, interestingly enough. Sounds like some coremod did something bad, but I dont know. The Errorlog doesnt give much information about this issue.

**Comment by bortooo** [comment] 2017-06-20 12:31
I found [this](https://pastebin.com/sSVTHPBf) in the log, maybe it could help.

**Comment by Xalcon** [comment] 2017-06-20 13:00
Thanks for that log, this actually contained the missing information. The issue is Galacticrafts Core Mod (Micdoodle Core), it wasnt able to transform a class properly. This class is needed by AnalyzeIO for the EnderIO dependency check though, which causes the crash.

`Potential problem: Galacticraft did not complete injection of bytecode into: bnz (4 / 6)`

```
[19:57:04] [Client thread/INFO]: [micdoodle8.mods.miccore.MicdoodleTransformer:printResultsAndReset:1521]: Potential problem: Galacticraft did not complete injection of bytecode into: bnz (4 / 6)
[19:57:04] [Client thread/INFO]: Patching net.minecraft.client.renderer.EntityRenderer... (bnz)
[19:57:04] [Client thread/INFO]: Patching net.minecraft.client.gui.GuiOptions... (bfn)
[19:57:05] [Client thread/INFO]: Patching net.minecraft.client.renderer.tileentity.TileEntityBeaconRenderer... (bqe)
[19:57:05] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Rendering screen
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1121) ~[bnz.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) ~[bcx.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NoClassDefFoundError: bxl
    at net.minecraftforge.fml.common.versioning.Restriction.toStringFriendly(Restriction.java:224) ~[Restriction.class:?]
    at net.minecraftforge.fml.common.versioning.VersionRange.toStringFriendly(VersionRange.java:498) ~[VersionRange.class:?]
    at net.minecraftforge.fml.client.GuiModsMissing.func_73863_a(GuiModsMissing.java:106) ~[GuiModsMissing.class:?]
    at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) ~[ForgeHooksClient.class:?]
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1094) ~[bnz.class:?]
    ... 9 more```

**Comment by bortooo** [comment] 2017-06-20 13:08
Thank! Should I report the issue to galacticraft?

**Comment by Xalcon** [comment] 2017-06-20 13:10
If this issue is happening on the latest version of galacticraft, yes. You can report it.
I dont know if the 1.10.2 version is still maintained though.

I will close this here then, we found the issue :)

**Closed as completed by Xalcon** 2017-06-20 13:10 UTC
Labels: can't reproduce

**Comment by bortooo** [comment] 2017-06-20 13:14
Ok thanks, but why you couldn't reproduce it?

**Comment by Xalcon** [comment] 2017-06-20 13:18
I dont know, maybe I was using different versions of mods. I think I had galacticraft 108 running while your crashlog showed 100. Maybe its this, no idea.

**Comment by bortooo** [comment] 2017-06-20 13:24
Now I have the same build and the issue doesn't appear, so I think they fixed it.
Thanks for your time!
